# Imagen base oficial de Python
FROM python:3.10-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia todos los archivos del proyecto al contenedor
COPY . .

# dependencias del proyecto
RUN pip install --upgrade pip && pip install -r requirements.txt

# Expone el puerto que usa Streamlit
EXPOSE 8501

# Ejecuta la app Streamlit
CMD ["streamlit", "run", "frontend/streamlit_app.py", "--server.port=8501", "--server.enableCORS=false"]